## 异步使用回调函数的形式进行图片加载
> 先一步创建加载图片的模块
> 把这个任务交给模块,(进入事件循环,这里是不准确的,要进一步了解任务管理的机制)
> js会首先执行主线程的指令
> 当主线程为空时,便会进入对象的任务队列

```js
        function imgloading(src, resolve, reject) {

            let img = new Image()

            img.src = src

            img.onload =()=>{

                resolve(img)

            }

            img.onerror = reject

            // 如果是打开节流,同步的缺点就出来了

            // 图片加载很慢的话我们就没有办法打印123

            // 但是事实确是打印直接就出来了

            // 这里我们使用事件来搞一个异步任务

        }

        imgloading("./images/2.jpg",(img)=>{

            document.body.appendChild(img)

            console.log("图片加载成功")

        },()=>{

            console.log("图片加载失败")

        })

        console.log(123)
```
## 定时器的轮询
> 首先封装一个定时器函数
> 让div每隔一定时间向右移动,到100px停止
> 然后让div缩小
> 然后开一个时间巨长的for 循环 
> 观察输出

```js
   function Interval(callback, delay = 100) {

            let id = setInterval(() => callback(id), delay)

        }

        // 首先你要看懂这个函数的解构

        // 传的参数是个函数,在Interval中会创建一个循环定时器,定时器隔一定时间调用callback

        // 当然我们的刚刚开始的时候不一定是看delay的延迟,如果主线程没有完成任务,异步也不会开始轮询

        Interval((timeid) => {

            // Window.getComputedStyle()原版使用了这个

            const div = document.querySelector("div")

            let left = div.offsetLeft

            div.style.left = left + 10 + 'px'

            if (left >= 800) {

                clearInterval(timeid)

                Interval((id) => {

                    let width = div.offsetWidth

                    div.style.width = width - 5 + 'px'

                    if (width < 20) {

                        clearInterval(id)

                    }

                })

            }

  
        })

        console.log(123);

        for (let i = 0; i < 50000; i++) {

            console.log(i)

        }
```

## 文件加载
```js
    <script>

        function loading(src, resolve) {

            let script = document.createElement("script")

            script.src = src

            script.onload = resolve

            document.body.appendChild(script)

        }

        loading("./js/one.js", () => {

            one()

        })

        loading("./js/two.js", () => {

            two()

        })

        // 我们使用同步方式书写这种异步加载

        // 会有一点小问题,有loading1和loading2的加载会有先后关系

        // 这样将导致先加载好的会先进入任务队列,如果loading先进入,就会出现error

        // 为了保证先后关系,只能写成嵌套的形式,但随着依赖关系的增加,代码会越来越复杂

        loading("./js/one.js", () => {

            one()

            loading("./js/two.js", () => {

                two()

            })

        })

        console.log(123)
```

多刷新几次就会有
![[进入任务之前是有一个加载关系的.png]]

## Ajax异步请求管理
```js
   // 导入的时候script标签type要注意一下

        import Ajax from "./js/ajax.js"

  

        Ajax("http://www.liulongbin.top:3006/api/getbooks", (result) => {

            let res = JSON.parse(result)

            console.log(JSON.parse(result))

            Ajax(`http://www.liulongbin.top:3006/api/getbooks?id=${res.data[0].id}`, (res) => {

                console.log(JSON.parse(result))

            })

        })

        console.log(123)
```
## Promise 微任务处理机制

```js
     <script>

            // Promise内部其实像一个厨房

            // 当厨房任务完成,会调用对应的状态方法

            // 如果事情没有完成Promise的状态就是pending

            // 如果事情完成且成功Promise的状态就是resolve

            // 如果事情完成,但是失败了Promise的状态就是reject

  

            console.log(new Promise((resolve, reject) => {

                resolve()

            }).then(res => {

                // then方法就是对应结果的处理

                console.log("权限验证成功")

            },

                error => {

                    console.log("权限验证失败")

                }))

            // Promise其实对应了微任务队列,微任务是先于宏任务的

        </script>
```

## 宏任务与微任务的执行机制
```js
ript>

        setTimeout(() => {

            console.log("settimeout")

        }, 0);

        console.log(123)
```

![[任务执行顺序1.png]]

```js
  new Promise((resolve,reject)=>{

            console.log("Promise中的代码也是同步任务")

        })

        console.log(123)
```

![[Pasted image 20230204175238.png]]

```js
 setTimeout(() => {

            console.log("settimeout")

        }, 0);

        new Promise((resolve, reject) => {

            resolve()

            console.log("Promise中的代码也是同步任务,then才是对应的微任务")

        }).then(res => {

            console.log("这里是微任务")

        })
        //这里就能看出微任务先于宏任务,一定要能区分各个不同的'角色'
        console.log(123)
```

![[Pasted image 20230204175940.png]]

## 宏任务提升原来是误会
```js
 let p = new Promise((resolve, reject) => {

                //    同步代码先执行,遇到settimeout先加入宏任务队列

                //    宏任务队列里的代码当然不会立即执行,先等主线程干完

                //    ,然后轮询微任务,但是没有,所以执行宏任务,当前任务队列里

                //    存在宏任务,所以先把第一个宏任务放到主线程执行(相当于同步了)

                setTimeout(() => {

                    console.log("setTimeout1")

                    reject()

                    console.log("setTimeout2")

                }, 0);

            }).then(res => {

                console.log("成功")

            }, error => {

                console.log("失败")

            })

            console.log(123);
```

## 单一状态与状态中转
```js
 let p = new Promise((resolve, reject) => {

            reject("success")

        })

        new Promise((resolve, reject) => {

            // resolve("成功")

            // 只有真正执行完resolve,才会抛出一个微任务

            // ,并且状态只能改变一次,任务的抛出是不可逆的

            // setTimeout(() => {

            //     resolve("成功")

            // }, 2000);

            // reject(p) 你用了失败,不管传递什么都是失败

            // resolve(p) n你用成功的话,如果你传递Promise,

            // 那么成功失败就有P决定

        }).then(res => {

            console.log(res)

        }, error => {

            console.log("error", error)

        })

        console.log(123);
```

## then 方法的基本使用
```js
 new Promise((resolve, reject) => {

                resolve("买了一瓶可乐")

            }).then(res => {

                console.log(res)

            }, error => {

                console.log(error)

            })
            //当你只关注某一种时,我们可以将另一个设为null
```
```js
 new Promise((resolve, reject) => {

                resolve("买了一瓶可乐")
			//当你有一个then为空的时候,你传递的'信号'会延续下去
            }).then().then(res => {

                console.log(res)

            }, error => {

                console.log(error)

            })
```

## then方法返回的是一个Promise
```js
let p1 = new Promise((resolve, reject) => {

                resolve("success")

            })

            let p2 = p1.then(res => {

                console.log("p2成功")

            }, error => {

                console.log("p2失败")

            })

            console.log(p1)

            console.log(p2)
		    // 首先执行同步,那么p1状态就是resolve
            // 但是then是微任务,所以,不会立即执行
            // 状态还是pending
```

![[Pasted image 20230204193503.png]]

```js
    let p1 = new Promise((resolve, reject) => {

                resolve("success")

            })

            let p2 = p1.then(res => {

                console.log("p2成功")

            }, error => {

                console.log("p2失败")

            })

            setTimeout(() => {

                console.log(p1)

                console.log(p2)

            }, 0);

            // 这里也一样,同步先执行,p1的状态就定了

            // 然后执行then,then方法默认会生成一个成功的promise,只不过里面的值是undefined
			//p1就算失败也默认成功
```

![[Pasted image 20230204194135.png]]

## then中返回值
```js
 new Promise((resolve,reject)=>{

            resolve("success")

        }).then(res=>{

            console.log(res)

            return "chenggong"

        },error=>{

            console.log(error)

        }).then(res=>{

            console.log(res)

        },error=>{

            console.log(error)

        })

        // then中你不返回promise,你返回的值是可以传递的

        // 你返回Promise的话,then所生成的promise就由你返回的 **(一定要return,不然下一级then拿不到这个promise)**

        // Promise决定,当然如果这个promise是pending,那后面的then

        // 是不会执行的
```

## then返回其他类型
```js
			class Person {

                constructor(name) {

                    this.name = name

                }

                then(resolve, reject) {

                    setTimeout(() => {

                        resolve("这是个类")

                    }, 2000);

                }

            }

            new Promise((resolve, reject) => {

                resolve()

            }).then(res => {

                // return {

                //     name: "name"

                // }

                // 你返回一个普通对象,没什么

                // return {

                //     then(resolve, reject) {

                //         setTimeout(() => {

                //             resolve("这是个对象")

                //         }, 2000);

                //     }

                // }

                // 但是一有个then,then还是像上面这么写

                // 这时他就会被封装为一个promise,具有promise的一切性质

                // return new Person("张三")

                return class {

                    static then(resolve, reject) {

                        setTimeout(() => {

                            resolve("这是个静态方法")

                        }, 2000);

                    }

                }

            }).then(res => {

                console.log(res)

            })

            // js会查找你这个返回的对象的原型,只要有then,还是有用的,就会被封装为一个Promise
```

## promise 发送Ajax
```js
  function Ajax(url) {

                return new Promise((resolve, reject) => {

                    let xhr = new XMLHttpRequest()

                    xhr.open("get", url)

                    xhr.send()

                    xhr.onreadystatechange = function () {

                        if (xhr.readyState == 4) {

                            if (xhr.status == 200) {

                                resolve(xhr.response)

                            } else {

                                reject(xhr.response)

                            }

                        }

                    }

                })

            }

            Ajax(`http://api.btstu.cn/qqol/api.php?qq=3184796337`)

                .then(res => {

                    console.log(res)

                    // 成功的话进一步获取昵称和头像

                    return Ajax(`http://api.btstu.cn/qqxt/api.php?qq=3184796337`)

                }, error => {

                    console.log(error)

                }).then((res)=>{

                    console.log(res);

                })
```

## Promise的错误处理
```js
 // new Promise((resolve, reject) => {

            //     //  首先有三种情况会自动调用reject

            //     // reject(new Error("这是第一种,直接传一个Error"))

            //     // 第二种直接跑了一个错误

            //     // throw new Error("直接抛出错误")

            //     // 第三种直接写错了

            //     // let + 1

            //     // 相当于内置了trycatch

            //     // try{

  

            //     // }catch(error){

            //     //     reject(error)

            //     // }

            //     resolve("success")

            // }).then(res => {

            //     console.log(res)

            //     return new Promise((resolve, reject) => {

            //         reject("fail")

            //     })

            // }, error => {

            //     console.log(error.message)

            // }).then(null, error => {

            //     console.log(error);

            // })

            new Promise((resolve, reject) => {

                reject("success")

            }).then(null, error => {

                console.log("error")

                return new Promise((resolve, reject) => {

                    reject("fail")

                })

            }).catch(error => {

                console.log(error);

            })

            // 你分开写的话如果出现错误,

            // 那么一个Promise对应一个then方法,对应一个错误的回调很麻烦

            // 但是用catch可以捕获所有的错误,而且如果你有错误的回调,

            // 会优先执行你的那个,你没有的他才会执行,我们可以对一些错误进行个性化处理

            // 别的一起干掉
```

## 用Promise处理前几个案例
1 . 封装settimeout
```js
    function timeout(delay) {

                return new Promise((resolve, reject) => {

                    setTimeout(() => {

                        resolve()

                    }, delay);

                })

            }

            timeout(2000).then(() => {

                console.log("定时器结束")

            })
```

2. 封装setinterval
```js
 function interval(delay = 400, callback) {

            return new Promise((resolve, reject) => {

                let id = setInterval(() => {

                    callback(id, resolve)

                }, delay);

  

            })

        }

        interval(100, (id, resolve) => {

            let box = document.querySelector(".box")

            let left = box.offsetLeft

            box.style.left = left + 'px'

            if (left > 600) {

                clearInterval(id)

                resolve(box)

            }

        }).then((box) => {

            interval(100, (id, resolve) => {

                let width = box.offsetWidth

                width -= 10

                box.style.width = width + 'px'

                if (width < 30) {

                    clearInterval(id)

                    resolve(box)

                }

            }).then((box) => {

                box.style.background = "pink"

            })

            // 总结就是可以让你的代码非常优雅

            // 一个then处理一个操作,

            // 超级丝滑,没有回调地狱的尴尬情况

        })
```
3. 异步加载图片
```js
   function loadimg(src) {

            return new Promise((resolve, reject) => {

                let image = new Image()

                image.src = src

                image.onload = () => {

                    resolve(image)

                }

                image.onerror = () => {

                    reject("图片加载出错")

                }

                document.body.appendChild(image)

            })

        }

        loadimg('./images/1.jpg')

            .then((image) => {

                image.style.border = "10px solid red"

            }).catch((error) => {

                console.log(error);

            })
```
## promise 的resolve方法,直接返回一个成功的Promise,缓存后台数据案例
```js
	 function Ajax(url) {

            return new Promise((resolve, reject) => {

                let xhr = new XMLHttpRequest()

                xhr.open("get", url)

                xhr.send()

                xhr.onreadystatechange = function () {

                    if (xhr.readyState == 4) {

                        if (xhr.status == 200) {

                            resolve(xhr.response)

                        } else {

                            reject("请求失败")

                        }

                    }

                }

            })

        }

        function getData(url) {

            let state = getData.state || (getData.state = new Map)

            if (state.has(msg)) {

                console.log("从缓存中获取数据")

                return Promise.resolve(state.get(msg))

            } else {

                return Ajax(url).then((res) => {

                    console.log("不走缓存");

                    getData.state.set("msg", JSON.parse(res).msg)

                    return JSON.parse(res).msg

                })

            }

        }

        getData(`http://api.btstu.cn/qqol/api.php?qq=3184796337`)

            .then((res) => {

                console.log(res);

            })

            // 要尽量翻个定时器,ajax是异步,你个getData有一部分是同步,同步的先来

            // 所以应该两个都是不走缓存

         setTimeout(() => {

            getData(`http://api.btstu.cn/qqol/api.php?qq=3184796337`)

            .then((res) => {

                console.log(res);

            })

         }, 1000);
```



## Promise 的reject方法
```js
 new Promise((resolve, reject) => {

                resolve("aaaaa")

            }).then((res) => {

                if (res != "bbbbb") {

                    throw new Error("错误")//这两句没啥区别

                }

                // return Promise.reject("错误")

  

            }).then((res) => {

                console.log(res);

            }).catch((error) => {

                console.log(error);

            })
```

## Promise.all方法
   当我们有多个Promise需要执行，且需要多个Promise都执行完毕，在将他们的结果进行统一处理时，我们便可以使用Promise.all来帮助我们完成这项工作。
   当遇到多个可以同时执行的异步任务时，就需要使用 `Promise.all`
```js
import Ajax from './js/promiseajax.js'

        // 来个例子

        const p1=new Promise((resolve,reject)=>{

            setTimeout(() => {

                resolve("aaaa")

            }, 1000);

        })

        const p2=new Promise((resolve,reject)=>{

            setTimeout(() => {

                resolve("bbbb")

            }, 1000);

        })

        // 上面两个Promise成功失败的回调都没有

        // 那个输入的所有 promise 的 resolve 回调的结果是一个数组。

        // 它的 reject 回调执行是，只要任何一个输入的 promise 的 reject 回调执行或者输入不合法的 promise

        // 就会立即抛出错误，并且 reject 的是第一个抛出的错误信息。

        Promise.all([p1,p2])

        .then((res)=>{

            console.log(res);

        }).catch((error)=>{

            console.log(error);

        })

        //批量获取qq在线状态

        console.log(Ajax)

        let list = [

            'http://api.btstu.cn/qqol/api.php?qq=3184796337',

            `http://api.btstu.cn/qqol/api.php?qq=1658537331`,

            `http://api.btstu.cn/qqol/api.php?qq=1791931780`]

        let promises = list.map((item) => {

            return Ajax(item)

        })

        Promise.all(promises)

            .then((res) => {

                console.log(res);

            }).catch((error) => {

                console.log(error)

            })
```

## Promise.allSettled的使用
1.   ![[Pasted image 20230208110631.png]]
2.  Promise.allSettled返回一个Promise（一定会成功），then他，可以得到关于原来Promise数组的一个对象数组，
```js
const p1 = new Promise((resolve, reject) => {

            setTimeout(() => {

                resolve("aaaa")

            }, 1000);

        })

        const p2 = new Promise((resolve, reject) => {

            setTimeout(() => {

                resolve("bbbb")

            }, 1000);

        })

  

        Promise.allSettled([p1,p2])

        .then((res)=>{

            console.log(res);

        }).catch((error)=>{

            console.log(error);

        })
```

## Promise.race
1. 来自MDN的例子
```js 
 var p1 = new Promise(function (resolve, reject) {

            setTimeout(resolve, 500, "one");

        });

        var p2 = new Promise(function (resolve, reject) {

            setTimeout(resolve, 100, "two");

        });

  

        Promise.race([p1, p2]).then(function (value) {

            console.log(value); // "two"

            // 两个都完成，但 p2 更快

        });

  

        var p3 = new Promise(function (resolve, reject) {

            setTimeout(resolve, 100, "three");

        });

        var p4 = new Promise(function (resolve, reject) {

            setTimeout(reject, 500, "four");

        });

  

        Promise.race([p3, p4]).then(function (value) {

            console.log(value); // "three"

            // p3 更快，所以它完成了

        }, function (reason) {

            // 未被调用

        });

  

        var p5 = new Promise(function (resolve, reject) {

            setTimeout(resolve, 500, "five");

        });

        var p6 = new Promise(function (resolve, reject) {

            setTimeout(reject, 100, "six");

        });

  

        Promise.race([p5, p6]).then(function (value) {

            // 未被调用

        }, function (reason) {

            console.log(reason); // "six"

            // p6 更快，所以它失败了

        });

```

2. 限制请求时间
```js
import Ajax from "./js/promiseajax.js"

        let p=new Promise((resolve,reject)=>{

            setTimeout(()=>{

                reject("已超时,该请求作废")

            },200)

        })

        Promise.race([Ajax('http://api.btstu.cn/qqol/api.php?qq=3184796337'),p])

        .then((res)=>{

            console.log(res)

        }).catch((error)=>console.log(error))
        
```

## Promise队列
```js
 import Ajax from "./promiseajax.js"

            // 分析./promiseajax.js

            // let p = Promise.resolve()

            // p.then((value)=>{

            //     console.log("这是一号任务")

            // }).then((value)=>{

            //     console.log("这是二号任务")

            // })

            // 这样子是同时出现,因为默认返回的Promise的状态就是success,就直接then了

            let p1 = Promise.resolve()

            // p1.then((value) => {

            //     return new Promise((resolve, reject) => {

            //         setTimeout(() => {

            //             console.log("这是一号任务")

            //             resolve()

            //         }, 2000);

            // // 但是这里我们是返回一个promise,那么后面的then就是最这个返回的进行处理,

            // // 我不改变状态的话,then是不会执行的,所以我只要在完成任务的时候改变状态就行

            //     })

            // }).then((value) => {

            //     return Promsie((resolve, reject) => {

            //         setTimeout(() => {

            //             console.log("这是二号任务")

            //             resolve()

            //         }, 2000)

            //     })

            // })

            let promise = Promise.resolve()

            promise = promise.then((res) => {

                return new Promise((resolve, reject) => {

                    setTimeout(() => {

                        console.log("这是三号")

                        resolve()

                    }, 2000)

                })

            })

            promise.then((res) => {

                new Promise((resolve, reject) => {

                    setTimeout(() => {

                        console.log("这是四号")

                    }, 2000)

                })

            })
```

## 实现Promise队列
```js
 function query(arr) {

            let promise = Promise.resolve()

            arr.map((item) => {

                promise = promise.then(_ => {

                    return new Promise((resolve, reject) => {

                        setTimeout(() => {

                            // item的第一件事,你当然还可以再次使用then,来做该项的第二件事

                            console.log(item)

                            resolve()

                        }, 1000);

                    })

                })
//感觉这样用map有点无语,毕竟没有返回值,相当于没有用map,foreach都行
            })

  

        }

        function query1(arr) {

            let p = Promise.resolve(111)

            for (let item of arr) {

                p = p.then((_ => {

                    return new Promise((resolve, reject) => {

                        setTimeout(() => {

                            console.log(item);

                            resolve()

                        }, 2000);

                    })

                }))

            }

        }

        function query3(arr) {

            arr.reduce((promise, item) => {

                return promise.then(_ => {

                    return new Promise((resolve, reject) => {

                        setTimeout(() => {

                            console.log(item)

                            resolve()

                        }, 1000);

                    })

                })

            },  Promise.resolve())

        }

        // query([1, 2, 3, 4, 5])

        //

        query3([1, 2, 3, 4, 5])
```
## 使用队列渲染数据
```js
 class User {

            Ajax(qq) {

                return Ajax(qq)

            }

            render(users) {

                users.reduce((promise, item) => {

                    return promise.then(_ => {

                        return this.Ajax(item)

                        console.log(item);

                    }).then(res => {

                        return new Promise((resolve, reject) => {

                            this.show(res.name)

                            resolve("success")

                        })

                    })

                }, Promise.resolve())

            }

            show(name) {

                let h2 = document.createElement("h2")

                h2.innerHTML = name

                document.body.appendChild(h2)

            }

        }

        // 草readyState写成onreadyState了

        new User().render(["3184796337", "2643315727"])
```

## async与await
### async的使用
```js
 async function fun() {

             //throw new Error("fail")  返回的是一个reject(),需要用catch或者then
            // let res =Promise.reject("123").then(null,(value)=>{})

        }

        // async 函数返回的必然是一个promise,没有返回值的话就没有用[[PromiseResult]]: undefined,但是状态依然是resolve
        // async 相当于  Promise.resolve("西游记"),当然你本来就返回一个Promise,那就和new Promise一样了
        //async当不返回Promise且没有错的时候,返回值一定是resolve
       
```

### await的使用
```js
async function fun1() {

            // let res =await "123"

            // let res =await new Error("fail")

            // let res =await new Promise((resolve,reject)=>{

            //     resolve(1111)

            // })

            // 相当于就是一个成功的Promise

            let res = await new Promise((resolve, reject) => {

                setTimeout(() => {

                    resolve(1111)//你不改变状态就直接卡住了,因为then就会卡主

                }, 2000);

            })

            console.log(res);

        }
```

## async 与await处理异步
```js 
         // async function getname() {

            //     let res = await Ajax(`http://api.btstu.cn/qqol/api.php?qq=3184796337`).then((state) => {

            //         return state

            //     }).then((res) => {

            //         return Ajax("http://api.btstu.cn/qqxt/api.php?qq=3184796337").then(data => {

            //           return   data.name

            //         })

            //     })

            //     return res

            // }

            // console.log(getname().then(res=>{

            //    console.log(res);

            // }));当然也不用特意拿出来

            // await厉害的地方就是可以直接拿到你那个resolve(value),传递的value
            //李老师那边解释的更好一点
```

## async 延时函数
```js
async function sleep(delay) {

            return new Promise((resolve, reject) => {

                setTimeout(() => {

                    resolve()

                }, delay);

            })

        }

        async function print(arr) {

            for (let value in arr) {

                await sleep(1000)

                console.log(value)

            }

        }

        print([1,2,3,4,5,6,7])
```

## async 加载进度条
```js
  function loading(users) {

            let progress=document.querySelector(".progress")

            users.forEach(async (user, index) => {

                let url = `http://api.btstu.cn/qqol/api.php?qq=${user}`

                let data = await Ajax(url)

                let width=(index+1)/users.length*100

                progress.style.width=width+"%"

                progress.innerHTML=Math.round(width)+"%"

                console.log(data);

            });

        }

        loading(["3184796337","3184796337","3184796337"])
```

## async 封装在类的内部
```js
 class User {

            async get(qq) {

                let data = Ajax(`http://api.btstu.cn/qqxt/api.php?qq=${qq}`)

                // 你要知道new那边的代码是同步的,有一个on的宏任务只有then才是微任务

                console.log(data);

                data.name += "123"

                console.log(data);

                // 这样写就是一个傻逼错误,首先Ajax返回的是promise

                // ,你这样是给promise添加一个属性

  
  

                // 比较OK的做法,res要传到外面的话,是不可以用返回值的形式

                // Ajax(`http://api.btstu.cn/qqxt/api.php?qq=${qq}`)

                //     .then(res => {

                //         res.name += "123"

                //         console.log(res)

                //     })

  
  

                // async await这样子就很好

                // let data = await Ajax(`http://api.btstu.cn/qqxt/api.php?qq=${qq}`)

                // data.name += "123"

                // console.log(data);

            }

        }

        new User().get("3184796337")
```

## class与await结合
```js
 class User {

            constructor(qq) {

                this.qq = qq

            }

            then(resolve, reject) {

                resolve(Ajax(`http://api.btstu.cn/qqol/api.php?qq=${this.qq}`))

            }

            // 当你在then中返回一个原型中具有then 的对象,他会被封装费一个promise

            // 而await就相当于then,所以new User(123)这个实力变相当于Promise,会调用then方法

            // 亲自去试一下

        }

        async function fn() {

            let res = await new User(3184796337)

            console.log(res, "AAAAAA");

        }

        fn()

        Promise.resolve()

            .then(_ => {

  

                return new User(3184796337)

            })

            .then(res => {

                console.log(res);

            })

        let res = Promise.resolve()

            .then(_ => {

  

                return new User(3184796337)

            })

        console.log(res);
```

## async和await的错误处理
### async的错误处理
```js
async function fn(){

            // return a

            // throw new Error("fail")

            return Promise.reject("123123")

        }

        fn().catch(error=>{

            console.log(error);

        })

        // 和原版promise没区别
```
## await的错误处理
```js
 async function fn(){

            try {

                console.log(111);

                let data=await Promise.reject("cuowu")

                // await后面一旦是一个reject:Promise.reject("cuowu"),

                // 就会抛错,会卡住try里的代码

                // let data =await new Promise((resolve,reject)=>{

                //     setTimeout(() => {

                //         reject("错误")

                //     }, 1000);

                // })

                console.log(222);

            } catch (error) {

                console.log(error);

            }

            console.log(333);

        }

        fn()
```
## await的同步执行
```js
async function task1() {

                return new Promise((resolve, reject) => {

                    setTimeout(() => {

                        resolve("task1")

                    }, 2000);

                })

            }

            async function task2() {

                return new Promise((resolve, reject) => {

                    setTimeout(() => {

                        resolve("task2")

                    }, 2000);

                })

            }

            async function test() {

                let p1 = task1()

                let p2 = task2()

                console.log(p1)

                console.log(p2)

                // 首先到这里是因为Promise中其实是同步的,而console是同步的

                // settimeout是宏任务,所以两个都是pending

                // 同时推入到定时器模块计时

                // 两秒后就resolve,await就是then

                console.log(await p1)

                console.log(await p2)

                // 这就是并行的手法,就是,相当于两个毫不相干的Promise

            }

            // test()

            async function test1() {

                console.log(Promise.all([task1(), task2()]));

                // 首先你要知道all方法时返回所有promise resolve的值，以数组的形式存放

                // 一旦有reject，就只能拿到第一个reject的信息

                let data = await Promise.all([task1(), task2()])

                console.log(data);

            }

            test1()
```

## 宏任务与微任务



## 定时器的任务编排
```js
 setTimeout(() => {

            console.log("定时器1执行");

        }, 0);

        setTimeout(() => {

            console.log("定时器2执行");

        }, 0);

        for(let i=0;i<10000;i++){

            console.log(" ")

        }

        // 这里就说明了,js在解析代码是:遇到定时器,

        // 便放入定时器管理模块开始计时,等到时间结束才会放入任务队列,

        // 同步代码执行完毕后,会按队列的形式,轮询

        // 千万注意定时器计时并不是主线程代码完毕才开始计时(这是一个巨大误区)
```







